#!/bin/csh
setenv XACT /persist/dev/xact
setenv JAVA_HOME /System/Library/Frameworks/JavaVM.framework/Versions/1.5/Home
setenv ANT_HOME /OtherApplications/apache-ant-1.7.0
setenv BDB_JAR /OtherApplications/db-4.6.21/build_unix/db.jar
setenv SERVLET_JAR /OtherApplications/apache-tomcat-6.0.14/lib/servlet-api.jar

setenv LOGS $XACT/var/logs
setenv WEBLOGS $XACT/var/weblogs
setenv SCRIPTS $XACT/dev/scripts
setenv SOURCE ${XACT}/dev/source
setenv OBJECT $XACT/var/object
setenv JAR $XACT/var/xact.jar
setenv TOOLS_JAR $JAVA_HOME/lib/tools.jar
setenv CLASSPATH ${JAR}:${TOOLS_JAR}:${BDB_JAR}:${SERVLET_JAR}
setenv DOC_OUT $XACT/var/doc
